riverqueue/river

- COPYING
- COPYING.lesser
- LICENSE.md
Hopefully I did this [correctly](https://choosealicense.com/licenses/lgpl-3.0/).
> add LGPLv3 license

- CHANGELOG.md
- docs/development.md
Also tweak the release instructions.
> changelog entry for v0.0.3 release

- client_test.go
- internal/dbsqlc/river_job.sql
- internal/dbsqlc/river_job.sql.go
- rescuer.go
- rescuer_test.go
I've been looking at ways we could start consolidating queries in
`river_job.sql` a bit because the file's currently quite a bit of a
mess. One pretty easy one that came out is that we multiple queries for
the rescuer that can be just one without much trouble.
Here, make that change, which also allows to simplify the rescuer's core
run loop by quite a bit and reduce the lines of code in there. Also
expect a slight performance improvement as we need only one round trip
to the database and the streamlined code lets us preallocate a number of
Go slices and reduce the number of `append`s happening.
> Refactor: Reduce rescuer LOCs / number of queries + optimize

- LICENSE
As discussed, this fixes compatibility with Go statically linked binaries. Fixes #47.
> change license to MPL-2.0

- .github/workflows/ci.yml
> run CI workflow on pull request too

- docs/README.md
Incorrect const used in the Readme.
Should be `QueueDefault` not `DefaultQueue`
> Readme use const QueueDefault

- client.go
> fix copy-pasted docs on DiscardedJobRetentionPeriod

- internal/maintenance/periodic_job_enqueuer.go
Here, aim to fix the intermittent test problem described in #215, in
which after inserting a periodic batch where periodic 500 ms jobs and
periodic 1500 ms jobs should've lined up, we come up with fewer 500 ms
jobs than expected, suggesting that only a 1500 ms job was inserted
during the run.
--- FAIL: TestPeriodicJobEnqueuer (0.00s)
--- FAIL: TestPeriodicJobEnqueuer/EnqueuesPeriodicJobs (1.57s)
logger.go:225: time=2024-02-19T07:53:42.969Z level=INFO msg="PeriodicJobEnqueuer: Run loop started"
periodic_job_enqueuer_test.go:112:
Error Trace:	/home/runner/work/river/river/internal/maintenance/periodic_job_enqueuer_test.go:82
/home/runner/work/river/river/internal/maintenance/periodic_job_enqueuer_test.go:112
Error:      	"[%!s(*dbsqlc.RiverJob=&{45 …
> Periodic job enqueuer: Keep timer paused around inserts to fix intermittency

- client_test.go
A first pass at trying to fix the problem described in #289, in which
what seems to be a finishing test produces an `i/o timeout` while trying
to insert a job.
I can't tell for sure, and this is another problem ~impossible to repro
locally, but I'm guessing the problem is that a cancelled context may
bubble up as a number of underlying problems in pgx, and this failure is
occurring because we're only checking against `context.Canceled`.
Here, modify the approach to check on `ctx.Err()` instead, and ignore
any insert problems if the parent context is indeed cancelled.
Fixes #289.
> Take a stab at fixing test with intermittent `i/o timeout` problem

- docs/README.md
Add a few more features to README in its feature list that have been
added more recently to the dot com documentation. Namely, multiple
queues and test helpers.
> Add a few more features to README

- rivertype/river_type.go
I happened to notice the other day that some types that have survived to
this day without being document are those in `JobState*`. Since the
purpose of each of these states isn't necessarily obvious based on their
name alone, document them and provide some useful details that may save
users from having to jump to the website or read source code.
> Document job states in `rivertype`

- client.go
- internal/dblist/db_list_test.go
- internal/dbunique/db_unique.go
- internal/maintenance/job_scheduler.go
- internal/maintenance/job_scheduler_test.go
- internal/maintenance/periodic_job_enqueuer.go
- internal/maintenance/periodic_job_enqueuer_test.go
- internal/riverinternaltest/riverdrivertest/riverdrivertest.go
- internal/util/dbutil/db_util.go
Small bit of follow up from #301.
> rename all instances of execTx to tx

- example_queue_pause_test.go
Adding this so I can link to it from docs.
> add example for queue pause and resume

- internal/riverinternaltest/startstoptest/startstoptest.go
An intermittent error that we observe reasonably frequently is an I/O
timeout that occurs while start/stopping a service hundreds of times,
and an error is returned as a Postgres connection was being established:
logger.go:257: time=2024-07-03T04:52:56.081Z level=INFO msg="Notifier: Listener connecting"
logger.go:257: time=2024-07-03T04:52:56.082Z level=INFO msg="Notifier: Listener connecting"
logger.go:257: time=2024-07-03T04:52:56.082Z level=ERROR msg="Notifier: Error connecting listener" err="write failed: write tcp 127.0.0.1:60976->127.0.0.1:5432: i/o timeout"
startstoptest.go:37:
Error Trace:	/home/runner/work/river/river/internal/riverinternaltest/startstoptest/startstoptest.go:37
/opt/hostedtoolcache/go/1.22.4/x64/src/runtime/asm_amd64.s:1695
Error:      	Received unexpected error: …
> Allow I/O timeout errors that fall out of stress tests

- internal/maintenance/periodic_job_enqueuer_test.go
This one continues #416. I fixed a pair of the `*AfterStart` tests, but
didn't look further to see that there were three more, and I guess by a
stroke of luck I was running GitHub Actions at the right time and didn't
encounter anymore failures (today I immediately started seeing them
again when pushing).
Rationale there is similar to #416:
* 500 ms is a short enough period that it seems to be possible in GitHub
Actions for that amount of time to have elapsed by the time we check
for the first set of jobs (amazing, I know, but I can't explain it any
other way).
* The way the tests are written, they're also very slow because each
requires waiting for one of the 500 ms periods to elapse, so the
minimum run time of each is 500 ms.
Technically, with the rewrites it can be argued that the test …
> Fix more flaky periodic job enqueuer `*AfterStart` tests

- CHANGELOG.md
- cmd/river/go.mod
- go.mod
- riverdriver/go.mod
- riverdriver/riverdatabasesql/go.mod
- riverdriver/riverpgxv5/go.mod
- rivershared/go.mod
Just an incremental release with a couple small changes in #690 and #691.
[skip ci]
> Release version 0.14.3

- client.go
- plugin.go
- plugin_test.go
- rivershared/riverpilot/pilot.go
Internal API restructuring to move added services to the pilot instead of the driver.
> refactor plugin system to pilot from driver

- CHANGELOG.md
- periodic_job.go
- periodic_job_test.go
closes https://github.com/riverqueue/river/issues/759
> update max time in NeverSchedule.Next method

- CHANGELOG.md
- cmd/river/go.mod
- go.mod
- riverdriver/go.mod
- riverdriver/riverdatabasesql/go.mod
- riverdriver/riverpgxv5/go.mod
- rivershared/go.mod
> prepare v0.18.0

- CHANGELOG.md
- cmd/river/go.mod
- go.mod
- riverdriver/go.mod
- riverdriver/riverdatabasesql/go.mod
- riverdriver/riverpgxv5/go.mod
- rivershared/go.mod
> prepare v0.20.0

- CHANGELOG.md
- cmd/river/go.mod
- go.mod
- riverdriver/go.mod
- riverdriver/riverdatabasesql/go.mod
- riverdriver/riverpgxv5/go.mod
- rivershared/go.mod
> prepare v0.20.1

- CHANGELOG.md
- cmd/river/go.mod
- go.mod
- riverdriver/go.mod
- riverdriver/riverdatabasesql/go.mod
- riverdriver/riverpgxv5/go.mod
- rivershared/go.mod
Preemptively preparing for release to ship #839.
[skip ci]
> prepare v0.20.2

- riverdriver/river_driver_interface.go
This is a Pro-only concern and isn't needed in this repo.
> remove riverdriver.ErrRetryTransaction

- client_test.go
- internal/riverinternaltest/retrypolicytest/retrypolicytest.go
We got a lot of the remaining intermittent test failures in #848, but
one that I was punting on because I couldn't immediately see the problem
is this one [1]:
--- FAIL: Test_Client_JobCompletion (0.00s)
--- FAIL: Test_Client_JobCompletion/JobThatReturnsErrIsRetryable (1.65s)
client_test.go:5561: Reusing idle schema "river_2025_04_26t03_40_43_schema_31" after cleaning in 194.808714ms [32 generated] [28 reused]
logger.go:256: time=2025-04-26T03:40:53.907Z level=INFO msg="River client started" client_id=fv-az1970-529_2025_04_26T03_40_53_541948
logger.go:256: time=2025-04-26T03:40:53.966Z level=WARN msg="jobexecutor.JobExecutor: Job errored; retrying" error=oops job_id=2 job_kind=callback
logger.go:256: time=2025-04-26T03:40:54.947Z level=INFO msg="maintenance.JobScheduler: Ran successfully" …
> Fix intermittent test failures checking job `retryable`
